#!/usr/bin/env bash
# This script prints "Best School" 10 times using a while loop, and says "Hi" after the 9th one.

counter=1
while [ $counter -le 10 ]
do
  echo "Best School"
  if [ $counter -eq 9 ]; then
    echo "Hi"
  fi
  ((counter++))
done
